# -*- coding: utf-8 -*-
"""global-data-center-and-ai-waterelectricity-usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ejxudt7NTHZgX0JTRHvCa_3xFnQxcyOt

# 1. Importação de bibliotecas
"""

import zipfile
import os
import pandas as pd
import time
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score)
from sklearn.ensemble import RandomForestRegressor

"""# 2. Download e carregamento dos dados"""

files.upload() #kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d ashyou09/global-data-center-and-ai-waterelectricity-usage

zip_name = "global-data-center-and-ai-waterelectricity-usage.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall(extract_path)

print("Arquivos extraídos:")
for f in os.listdir(extract_path):
    print(f)

"""# 3. Análise exploratória"""

df = pd.read_csv("/content/dataset/data_center_hybrid.csv")

print(df.shape)

df.head()

df.columns

"""## 3.1. Remoção de colunas irrelevantes"""

X = df.drop(['Daily_Water_Usage_Gallons', 'Facility_ID', 'Facility_Name', 'Owner_Company', 'City'], axis=1)

y = df['Daily_Water_Usage_Gallons']

X.columns

X.info()

X.describe()

X.isnull().sum()

"""# 4. Pré-processamento

"""

#machine learning não aceita texto diretamente
X = pd.get_dummies(X, columns=['Facility_Type', 'Cooling_System_Type', 'Country', 'Surrounding_Water_Stress_Tier'])

"""# 5. Separa dados para treino, teste e validação"""

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=42)

print(f"Treino: {len(X_train)} porcentagem ({len(X_train)/len(X)*100:.1f}%)")
print(f"Validação: {len(X_val)} porcentagem ({len(X_val)/len(X)*100:.1f}%)")
print(f"Teste: {len(X_test)} porcentagem ({len(X_test)/len(X)*100:.1f}%)")

"""# 6. Regressão linear

## 6.1. Treinamento
"""

modelo_lr = LinearRegression()

inicio_treino_lr = time.time()

modelo_lr.fit(X_train, y_train)

fim_treino_lr = time.time()

tempo_treino_lr = fim_treino_lr - inicio_treino_lr

print(f"Tempo de treinamento: {tempo_treino_lr:.4f} segundos")

"""## 6.2. Avaliação"""

inicio_predicao_lr = time.time()

y_pred_val_lr = modelo_lr.predict(X_val)

fim_predicao_lr = time.time()

tempo_pred_lr = fim_predicao_lr - inicio_predicao_lr

print(f"Tempo de predição: {tempo_pred_lr:.4f} segundos")

mae_lr = mean_absolute_error(y_val, y_pred_val_lr)

rmse_lr = mean_squared_error(y_val, y_pred_val_lr) ** 0.5

r2_lr = r2_score(y_val, y_pred_val_lr)

print("REGRESSÃO LINEAR")
print(f"  MAE: {mae_lr:.2f}")
print(f"  RMSE: {rmse_lr:.2f}")
print(f"  R²: {r2_lr:.4f}")

"""### 6.2.1. Gráficos"""

plt.figure(figsize=(8,6))

plt.scatter(y_val, y_pred_val_lr, alpha=0.4, color='blue', label='Valores Previstos')

min_val = min(y_val.min(), y_pred_val_lr.min())
max_val = max(y_val.max(), y_pred_val_lr.max())
plt.plot([min_val, max_val], [min_val, max_val], color='red', label='Previsão Perfeita')

plt.xlabel("Valor real")
plt.ylabel("Valor previsto")

plt.title("Regressão linear: Real vs Previsto")
plt.legend()
plt.grid(True)
plt.show()

"""# 7. Random Forest

## 7.1 Treinamento e avaliação
"""

resultados = []

for n in [10, 50, 100]:
  modelo_rf = RandomForestRegressor(n_estimators = n)

  inicio_treino_rf = time.time()

  modelo_rf.fit(X_train, y_train)

  fim_treino_rf = time.time()

  tempo_treino_rf = fim_treino_rf - inicio_treino_rf

  #avaliacao
  inicio_predicao_rf = time.time()

  y_pred_val_rf = modelo_rf.predict(X_test)

  fim_predicao_rf = time.time()

  tempo_pred_rf = fim_predicao_rf - inicio_predicao_rf

  mae_rf = mean_absolute_error(y_test, y_pred_val_rf)

  rmse_rf = mean_squared_error(y_test, y_pred_val_rf) ** 0.5

  r2_rf = r2_score(y_test, y_pred_val_rf)

  resultados.append([n, tempo_treino_rf, tempo_pred_rf, mae_rf, rmse_rf, r2_rf])

"""### 7.1.1. Resultados"""

pd.DataFrame(resultados, columns=['n_estimators', 'tempo_treino', 'tempo_pred', 'mae_rf', 'rmse_rf', 'r2_rf'])