# -*- coding: utf-8 -*-
"""global-data-center-and-ai-waterelectricity-usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ejxudt7NTHZgX0JTRHvCa_3xFnQxcyOt
"""

import zipfile
import os
import pandas as pd
from google.colab import files
from sklearn.model_selection import train_test_split

"""Download e carregamento dos dados"""

files.upload() #kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d ashyou09/global-data-center-and-ai-waterelectricity-usage

zip_name = "global-data-center-and-ai-waterelectricity-usage.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall(extract_path)

print("Arquivos extraídos:")
for f in os.listdir(extract_path):
    print(f)

"""Análise exploratória"""

df = pd.read_csv("/content/dataset/data_center_hybrid.csv")

print(df.shape)

df.head()

df.columns

X = df.drop(['Daily_Water_Usage_Gallons', 'Facility_ID', 'Facility_Name', 'Owner_Company', 'City'], axis=1)

y = df['Daily_Water_Usage_Gallons']

X.columns

X.info()

X.describe()

X.isnull().sum()

"""Pré-processamento

"""

#machine learning não aceita texto diretamente
X = pd.get_dummies(X, columns=['Facility_Type', 'Cooling_System_Type', 'Country', 'Surrounding_Water_Stress_Tier'])

"""Separa dados para treino e teste"""

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=42)

print(f"Treino: {len(X_train)} porcentagem ({len(X_train)/len(X)*100:.1f}%)")
print(f"Validação: {len(X_val)} porcentagem ({len(X_val)/len(X)*100:.1f}%)")
print(f"Teste: {len(X_test)} porcentagem ({len(X_test)/len(X)*100:.1f}%)")