# -*- coding: utf-8 -*-
"""global-data-center-and-ai-waterelectricity-usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ibfw7Mqx_iFh9NA9r0WoIlTKmAycTntA

# 1. Importação de bibliotecas
"""

import zipfile
import os
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score)
from sklearn.ensemble import RandomForestRegressor

"""# 2. Download e carregamento dos dados"""

files.upload() #kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d ashyou09/global-data-center-and-ai-waterelectricity-usage

zip_name = "global-data-center-and-ai-waterelectricity-usage.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall(extract_path)

print("Arquivos extraídos:")
for f in os.listdir(extract_path):
    print(f)

"""# 3. Análise exploratória"""

df = pd.read_csv("/content/dataset/data_center_hybrid.csv")

print(df.shape)

df.head()

df.columns

"""## 3.1. Remoção de colunas irrelevantes"""

X = df.drop(['Daily_Water_Usage_Gallons', 'Facility_ID', 'Facility_Name', 'Owner_Company', 'City'], axis=1)

y = df['Daily_Water_Usage_Gallons']

X.columns

X.info()

X.describe()

X.isnull().sum()

"""# 4. Pré-processamento

"""

#machine learning não aceita texto diretamente
X = pd.get_dummies(X, columns=['Facility_Type', 'Cooling_System_Type', 'Country', 'Surrounding_Water_Stress_Tier'])

"""# 5. Execução com 30 sementes diferentes

## 5.1. Regressão Linear — 30 sementes
"""

sementes = list(range(30))
n_estimators_fixo = 100

resultados_lr = []

for seed in sementes:
    X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=seed)
    X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=seed)

    modelo_lr = LinearRegression()

    inicio_treino_lr = time.time()
    modelo_lr.fit(X_train, y_train)
    fim_treino_lr = time.time()
    tempo_treino_lr = fim_treino_lr - inicio_treino_lr

    inicio_predicao_lr = time.time()
    y_pred_val_lr = modelo_lr.predict(X_val)
    fim_predicao_lr = time.time()
    tempo_pred_lr = fim_predicao_lr - inicio_predicao_lr

    mae_lr = mean_absolute_error(y_val, y_pred_val_lr)
    rmse_lr = mean_squared_error(y_val, y_pred_val_lr) ** 0.5
    r2_lr = r2_score(y_val, y_pred_val_lr)

    resultados_lr.append({'seed': seed, 'mae': mae_lr, 'rmse': rmse_lr, 'r2': r2_lr, 'tempo_treino': tempo_treino_lr, 'tempo_predicao': tempo_pred_lr})

df_lr = pd.DataFrame(resultados_lr)

print("REGRESSÃO LINEAR (resultados por semente)")
print(df_lr.to_string(index=False))

print("\nREGRESSÃO LINEAR (estatísticas)")
print(df_lr[['mae', 'rmse', 'r2', 'tempo_treino', 'tempo_predicao']].agg(['mean', 'std', 'min', 'max']))

"""### 5.1.1. Gráfico — R² da Regressão Linear por semente

"""

plt.figure(figsize=(12, 4))
plt.plot(df_lr['seed'], df_lr['r2'], marker='o', label='R² por semente')
plt.axhline(df_lr['r2'].mean(), color='red', linestyle='--', label=f"Média R² = {df_lr['r2'].mean():.4f}")
plt.xlabel("Semente")
plt.ylabel("R²")
plt.title("Regressão Linear: R² por Semente")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""### 5.1.2. Gráfico — Real vs Previsto (última semente)


"""

plt.figure(figsize=(8, 6))
plt.scatter(y_val, y_pred_val_lr, alpha=0.4, color='blue', label='Valores Previstos')
min_val = min(y_val.min(), y_pred_val_lr.min())
max_val = max(y_val.max(), y_pred_val_lr.max())
plt.plot([min_val, max_val], [min_val, max_val], color='red', label='Previsão Perfeita')
plt.xlabel("Valor real")
plt.ylabel("Valor previsto")
plt.title(f"Regressão Linear: Real vs Previsto (semente {sementes[-1]})")
plt.legend()
plt.grid(True)
plt.show()

"""## 5.2. Random Forest — 30 sementes


"""

resultados_rf = []

for seed in sementes:
    X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=seed)
    X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=seed)

    modelo_rf = RandomForestRegressor(n_estimators=n_estimators_fixo, random_state=seed)

    inicio_treino_rf = time.time()
    modelo_rf.fit(X_train, y_train)
    fim_treino_rf = time.time()
    tempo_treino_rf = fim_treino_rf - inicio_treino_rf

    inicio_predicao_rf = time.time()
    y_pred_val_rf = modelo_rf.predict(X_val)
    fim_predicao_rf = time.time()
    tempo_pred_rf = fim_predicao_rf - inicio_predicao_rf

    mae_rf = mean_absolute_error(y_val, y_pred_val_rf)
    rmse_rf = mean_squared_error(y_val, y_pred_val_rf) ** 0.5
    r2_rf = r2_score(y_val, y_pred_val_rf)

    resultados_rf.append({'seed': seed, 'n_estimators': n_estimators_fixo, 'mae': mae_rf, 'rmse': rmse_rf, 'r2': r2_rf, 'tempo_treino': tempo_treino_rf, 'tempo_predicao': tempo_pred_rf})

df_rf = pd.DataFrame(resultados_rf)

print("RANDOM FOREST (resultados por semente)")
print(df_rf.to_string(index=False))

print("\nRANDOM FOREST (estatísticas)")
print(df_rf[['mae', 'rmse', 'r2', 'tempo_treino', 'tempo_predicao']].agg(['mean', 'std', 'min', 'max']))

"""### 5.2.1. Gráfico — R² do Random Forest por semente

"""

plt.figure(figsize=(12, 4))
plt.plot(df_rf['seed'], df_rf['r2'], marker='o', label='R² por semente')
plt.axhline(df_rf['r2'].mean(), color='red', linestyle='--', label=f"Média R² = {df_rf['r2'].mean():.4f}")
plt.xlabel("Semente")
plt.ylabel("R²")
plt.title(f"Random Forest (n={n_estimators_fixo}): R² por Semente")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""### 5.2.2. Gráfico — Real vs Previsto (última semente)


"""

plt.figure(figsize=(8, 6))
plt.scatter(y_val, y_pred_val_rf, alpha=0.4, color='blue', label='Valores Previstos')
min_val = min(y_val.min(), y_pred_val_rf.min())
max_val = max(y_val.max(), y_pred_val_rf.max())
plt.plot([min_val, max_val], [min_val, max_val], color='red', label='Previsão Perfeita')
plt.xlabel("Valor real")
plt.ylabel("Valor previsto")
plt.title(f"Random Forest: Real vs Previsto (semente {sementes[-1]})")
plt.legend()
plt.grid(True)
plt.show()

"""### 5.2.3. Importância de variáveis (última semente)"""

importancias = modelo_rf.feature_importances_
df_importancias = pd.DataFrame({'Variavel': X.columns, 'Importancia': importancias})
df_importancias = df_importancias.sort_values(by='Importancia', ascending=False)

print(df_importancias.head(10))

top5 = df_importancias.head(5)
plt.figure(figsize=(10, 6))
plt.barh(top5['Variavel'], top5['Importancia'])
plt.xlabel('Importância')
plt.ylabel('Variável')
plt.title('Top 5 Variáveis Mais Importantes')
plt.gca().invert_yaxis()
plt.show()

"""## 5.3. Variação do n_estimators do Random Forest (última semente)"""

seed_final = sementes[-1]
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=seed_final)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=seed_final)

resultados_n = []

for n in [10, 50, 100, 150]:
    modelo_rf_n = RandomForestRegressor(n_estimators=n, random_state=seed_final)

    inicio_treino_rf = time.time()
    modelo_rf_n.fit(X_train, y_train)
    fim_treino_rf = time.time()
    tempo_treino_rf = fim_treino_rf - inicio_treino_rf

    inicio_predicao_rf = time.time()
    y_pred_n = modelo_rf_n.predict(X_val)
    fim_predicao_rf = time.time()
    tempo_pred_rf = fim_predicao_rf - inicio_predicao_rf

    resultados_n.append([n, tempo_treino_rf, tempo_pred_rf, mean_absolute_error(y_val, y_pred_n), mean_squared_error(y_val, y_pred_n) ** 0.5, r2_score(y_val, y_pred_n)])

df_n = pd.DataFrame(resultados_n, columns=['n_estimators', 'tempo_treino', 'tempo_pred', 'mae_rf', 'rmse_rf', 'r2_rf'])
print(df_n)

"""# 6. Comparação entre LR e RF (média das 30 sementes)"""

comparacao = pd.DataFrame({
    'Modelo': ['Regressão Linear', 'Random Forest'],
    'MAE (média)': [df_lr['mae'].mean(), df_rf['mae'].mean()],
    'MAE (std)': [df_lr['mae'].std(), df_rf['mae'].std()],
    'RMSE (média)': [df_lr['rmse'].mean(), df_rf['rmse'].mean()],
    'RMSE (std)': [df_lr['rmse'].std(), df_rf['rmse'].std()],
    'R² (média)': [df_lr['r2'].mean(), df_rf['r2'].mean()],
    'R² (std)': [df_lr['r2'].std(), df_rf['r2'].std()],
    'Tempo treino (média s)': [df_lr['tempo_treino'].mean(), df_rf['tempo_treino'].mean()],
    'Tempo pred (média s)': [df_lr['tempo_predicao'].mean(),df_rf['tempo_predicao'].mean()]})

print(comparacao.to_string(index=False))

"""## 6.1. Gráfico — distribuição do R² (boxplot)"""

plt.figure(figsize=(8, 6))
plt.boxplot(
    [df_lr['r2'].values, df_rf['r2'].values],
    tick_labels=['Regressão Linear', 'Random Forest'],
    patch_artist=True,
    boxprops=dict(facecolor='lightblue'),
)
plt.ylabel("R²")
plt.title("Distribuição do R² — 30 sementes")
plt.grid(True, axis='y')
plt.tight_layout()
plt.show()

"""## 6.2. Gráfico — R² médio por modelo"""

plt.figure(figsize=(6, 5))
plt.bar(
    comparacao['Modelo'],
    comparacao['R² (média)'],
    yerr=comparacao['R² (std)'],
    capsize=5,
    color=['steelblue', 'forestgreen'],
)
plt.ylabel("R² médio")
plt.title("Comparação dos Modelos — média de 30 sementes")
plt.tight_layout()
plt.show()

"""## 6.3 Gráfico — Real vs Previsto"""

fig, ax = plt.subplots(figsize=(10, 7))

ax.scatter(y_val, y_pred_val_lr, alpha=0.4, color='blue', label='Regressão Linear')
ax.scatter(y_val, y_pred_val_rf, alpha=0.4, color='green', label='Random Forest')

min_val = min(y_val.min(), y_pred_val_lr.min(), y_pred_val_rf.min())
max_val = max(y_val.max(), y_pred_val_lr.max(), y_pred_val_rf.max())
ax.plot([min_val, max_val], [min_val, max_val], color='red', linewidth=1.5, label='Previsão Perfeita')

ax.set_xlabel("Valor real")
ax.set_ylabel("Valor previsto")
ax.set_title(f"Real vs Previsto — Regressão Linear e Random Forest (semente {sementes[-1]})")
ax.legend()
ax.grid(True)
plt.tight_layout()
plt.show()